FROM golang:1.13-alpine AS build_base

RUN apk add --no-cache git
RUN apk update && apk add g++ gcc libxml2 libxslt-dev

# Set the Current Working Directory inside the container
WORKDIR /tmp/einvoice

# Populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

# Unit tests
# RUN CGO_ENABLED=0 go test -v ./apiserver

RUN go build -o /tmp/out/apiserver ./apiserver

# Start fresh from a smaller image
FROM alpine:3.9
RUN apk add ca-certificates
RUN apk update && apk add libxml2 libxslt-dev

COPY --from=build_base /tmp/out/apiserver /app/apiserver
COPY --from=build_base /tmp/einvoice/sql /sql
COPY --from=build_base /tmp/einvoice/xml /xml

# This container exposes port 8080 to the outside world
EXPOSE 8080

CMD ["/app/apiserver"]